name: Laravel CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Tentukan versi PHP yang sesuai dengan aplikasi Anda
        extensions: mbstring, intl, bcmath, gd, zip

    - name: Install dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Set up environment file
      run: cp .env.example .env  # Salin file .env.example ke .env untuk konfigurasi lingkungan

    - name: Generate Laravel application key
      run: php artisan key:generate  # Membuat aplikasi key Laravel

    - name: Run tests
      run: php artisan test --env=testing  # Jalankan tes menggunakan environment testing
