name: Laravel CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        options: --env MYSQL_ROOT_PASSWORD= --env MYSQL_DATABASE=pemwebuas
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  
        extensions: mbstring, intl, bcmath, gd, zip, pdo, mysql

    - name: Install dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Create .env file
      run: |
        echo "APP_NAME=Laravel" > .env
        echo "APP_ENV=testing" >> .env
        echo "APP_KEY=base64:$(php artisan key:generate --show)" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=mysql" >> .env  # Gunakan nama layanan 'mysql' untuk menghubungkan ke MySQL
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=pemwebuas" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=" >> .env  # Password MySQL

    - name: Wait for MySQL to be ready
      run: |
        until mysql -h mysql -u root -pyour_password_here -e "SELECT 1"; do  # Ganti dengan nama layanan 'mysql'
          echo "Waiting for MySQL to be ready..."
          sleep 5  # Tingkatkan waktu tunggu untuk memberikan MySQL lebih banyak waktu
        done

    - name: Run tests
      run: php artisan test --env=testing
